// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARmz5_lLXCwxxIOgcWU9CyD4YOBaTtdDc',
    appId: '1:590390456686:web:fc4a02ffa3466a0a87117f',
    messagingSenderId: '590390456686',
    projectId: 'hotelproject-84217',
    authDomain: 'hotelproject-84217.firebaseapp.com',
    storageBucket: 'hotelproject-84217.appspot.com',
    measurementId: 'G-B7FDTDZ4XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaWHKdVLg3JJIlt-ItFLLo0J7rMOGsVs0',
    appId: '1:590390456686:android:cd62846663c0cd4887117f',
    messagingSenderId: '590390456686',
    projectId: 'hotelproject-84217',
    storageBucket: 'hotelproject-84217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIKcMzRrQOFNwSjKi6EMcG-9_xvwH8k7o',
    appId: '1:590390456686:ios:14c28cfd41ce6ceb87117f',
    messagingSenderId: '590390456686',
    projectId: 'hotelproject-84217',
    storageBucket: 'hotelproject-84217.appspot.com',
    androidClientId: '590390456686-ffb8ntk74pv1qn1am9jtqjf0opt4k5hk.apps.googleusercontent.com',
    iosClientId: '590390456686-gen567ka11htrs2av1vj5vs0hrpnniiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIKcMzRrQOFNwSjKi6EMcG-9_xvwH8k7o',
    appId: '1:590390456686:ios:14c28cfd41ce6ceb87117f',
    messagingSenderId: '590390456686',
    projectId: 'hotelproject-84217',
    storageBucket: 'hotelproject-84217.appspot.com',
    androidClientId: '590390456686-ffb8ntk74pv1qn1am9jtqjf0opt4k5hk.apps.googleusercontent.com',
    iosClientId: '590390456686-gen567ka11htrs2av1vj5vs0hrpnniiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARmz5_lLXCwxxIOgcWU9CyD4YOBaTtdDc',
    appId: '1:590390456686:web:f88c66c63028613f87117f',
    messagingSenderId: '590390456686',
    projectId: 'hotelproject-84217',
    authDomain: 'hotelproject-84217.firebaseapp.com',
    storageBucket: 'hotelproject-84217.appspot.com',
    measurementId: 'G-JJ6DWDV2SD',
  );
}
